version: "3"
services:
  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-pd
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
