name: Security OWASP dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "7 4 * * MON-FRI" # Every weekday at 04:07 UTC
jobs:
  security-kotlin-owasp-check:
    name: Kotlin security OWASP dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_owasp.yml@pgp-SDIT-2050-allow-subprojects
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
